# -*- coding: utf-8 -*-
"""
Created on Fri Jan 12 15:03:52 2018

@author: 3301269
"""

from kmer import *
import sys
import os

if __name__ == "__main__":
	matrix = np.load("matrice_dist_jsdiv_GLOBAL_Chaos_archaea_6_100000.npy")
	plt.figure()
	plot_matrice_distance(matrix)
	plt.show()
	names_bac = ["Acholeplasma_laidlawii_PG-8A","Acidobacterium_capsulatum_ATCC_51196","Akkermansia_muciniphila_ATCC_BAA-835","Alicyclobacillus_acidocaldarius_subsp._acidocaldarius_DSM_446_plasmid_pAACI02","Aquifex_aeolicus_VF5","Bacillus_cereus_Q1_plasmid_pBc53","Bacillus_pseudofirmus_OF4","Bacteroides_fragilis_YCH46_DNA","Bdellovibrio_bacteriovorus_complete_genome","Bordetella_pertussis_strain_Tohama_I","Borrelia_burgdorferi_B31_plasmid_cp32-6","Campylobacter_jejuni_subsp._jejuni_81-176_plasmid_pTet","Candidatus_Amoebophilus_asiaticus_5a2","Candidatus_Cloacamonas_acidaminovorans_str._Evry_provisional_genome_sequence_from_WWE1_candidate_division","Candidatus_Endomicrobium_trichonymphae_plasmid_pRSTT1_DNA","Candidatus_Solibacter_usitatus_Ellin6076_chromosome","Carboxydothermus_hydrogenoformans_Z-2901","Chlamydia_trachomatis_strain_L2_434_Bu_complete_genome","Chlorobium_chlorochromatii_CaD3","Chloroflexus_aurantiacus_J-10-fl","Clostridium_acetobutylicum_ATCC_824_megaplasmid_pSOL1","Corynebacterium_glutamicum_ATCC_13032","Corynebacterium_glutamicum_ATCC_13032_DNA","Coxiella_burnetii_RSA_493_plasmid_pQpH1","Cyanothece_sp._ATCC_51142_plasmid_C","Dehalococcoides_mccartyi_195_chromosome","Deinococcus_radiodurans_R1_chromosome_2","Deinococcus_radiodurans_R1_plasmid_MP1","Dictyoglomus_thermophilum_H-6-12","Elusimicrobium_minutum_Pei191","Fibrobacter_succinogenes_subsp._succinogenes_S85","Flavobacterium_psychrophilum_JIP02_86_complete_genome","Fusobacterium_nucleatum_subsp._nucleatum_ATCC_25586","Gemmatimonas_aurantiaca_T-27_DNA","Gloeobacter_violaceus_PCC_7421_DNA","Leptospira_interrogans_serovar_Lai_str._56601_chromosome_I","Magnetococcus_marinus_MC-1","Methylacidiphilum_infernorum_V4","Mycoplasma_genitalium_G37","Nostoc_punctiforme_PCC_73102","Opitutus_terrae_PB90-1","Pedobacter_heparinus_DSM_2366","Pirellula_staleyi_DSM_6068","Prochlorococcus_marinus_str._AS9601","Psychrobacter_arcticus_273-4","Rhizobium_leguminosarum_bv._trifolii_WSM1325_plasmid_pR132502","Rhodopirellula_baltica_SH_1_complete_genome","Rhodospirillum_rubrum_ATCC_11170","Rickettsia_rickettsii_str._Iowa","Shewanella_putrefaciens_CN-32","Synechococcus_elongatus_PCC_6301_DNA","Thermanaerovibrio_acidaminovorans_DSM_6589","Thermoanaerobacter_tengcongensis_MB4","Thermobaculum_terrenum_ATCC_BAA-798_chromosome_1","Thermodesulfovibrio_yellowstonii_DSM_11347","Thermomicrobium_roseum_DSM_5159_plasmid","Thermotoga_maritima_MSB8","Thermus_thermophilus_HB8_plasmid_pTT27_DNA"]
	names_archeas = ["Aeropyrum_pernix_K1_DNA","Archaeoglobus_fulgidus_DSM_4304","Archaeoglobus_profundus_DSM_5631","Caldivirga_maquilingensis_IC-167","Candidatus_Korarchaeum_cryptofilum_OPF8","Desulfurococcus_kamchatkensis_1221n","Haloarcula_marismortui_ATCC_43049_plasmid_pNG100","Halobacterium_sp._NRC-1","Halomicrobium_mukohataei_DSM_12286","Haloquadratum_walsbyi_DSM_16790_complete_genome","Halorhabdus_utahensis_DSM_12940","Halorubrum_lacusprofundi_ATCC_49239_chromosome_2","Haloterrigena_turkmenica_DSM_5511_plasmid_pHTUR04","Hyperthermus_butylicus_DSM_5456","Ignicoccus_hospitalis_KIN4_I","Metallosphaera_sedula_DSM_5348","Methanobrevibacter_ruminantium_M1","Methanobrevibacter_smithii_ATCC_35061","Methanocaldococcus_fervens_AG86_plasmid_pMEFER01","Methanocella_paludicola_SANAE_DNA","Methanococcoides_burtonii_DSM_6242","Methanococcus_aeolicus_Nankai-3","Methanococcus_maripaludis_C6","Methanococcus_vannielii_SB","Methanocorpusculum_labreanum_Z","Methanoculleus_marisnigri_JR1","Methanohalophilus_halophilus_strain_Z-7982_chromosome","Methanopyrus_kandleri_AV19","Methanoregula_boonei_6A8_chromosome","Methanosaeta_thermophila_PT","Methanosarcina_acetivorans_str._C2A","Methanosarcina_barkeri_str._Fusaro","Methanosarcina_mazei_strain_Goe1","Methanosphaera_stadtmanae_DSM_3091","Methanosphaerula_palustris_E1-9c_chromosome","Methanospirillum_hungatei_JF-1","Nanoarchaeum_equitans_Kin4-M","Natronomonas_pharaonis_DSM_2160_plasmid_PL131_complete_genome","Nitrosopumilus_maritimus_SCM1","Picrophilus_torridus_DSM_9790","Pyrobaculum_aerophilum_str._IM2","Pyrobaculum_arsenaticum_DSM_13514","Pyrobaculum_neutrophilum_V24Sta_chromosome","Pyrococcus_abyssi_complete_genome","Pyrococcus_furiosus_DSM_3638","Pyrococcus_horikoshii_OT3_DNA","Staphylothermus_marinus_F1","Sulfolobus_acidocaldarius_DSM_639","Sulfolobus_solfataricus_P2","Thermococcus_gammatolerans_EJ3","Thermofilum_pendens_Hrk_5","Thermoplasma_acidophilum_DSM_1728_complete_genome","Thermoplasma_volcanium_GSS1_DNA"]
	np.savetxt("distancematrix.csv", matrix, header = ",".join(names_archeas),delimiter = ",") #A transposer avec le code awk et a rajouter des headers (noms espaces separés par , et avec une , avant premier nom), pour pouvoir faire NJ